force-app/main/default/objects/Solution__c/Solution__c.object-meta.xml
<CustomObject>
    <label>Solution</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Solution__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>API</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/domain/services/SolutionService.cls
public with sharing class SolutionService {

    public void processSolutionByType(List<Solution__c> solutions) {
        List<Solution__c> apiSolutions = new List<Solution__c>();
        List<Solution__c> softwareSolutions = new List<Solution__c>();
        List<Solution__c> serviceSolutions = new List<Solution__c>();

        for (Solution__c solution : solutions) {
            if (solution.Type__c == SolutionConstants.TYPE_API) {
                apiSolutions.add(solution);
            } else if (solution.Type__c == SolutionConstants.TYPE_SOFTWARE) {
                softwareSolutions.add(solution);
            } else if (solution.Type__c == SolutionConstants.TYPE_SERVICE) {
                serviceSolutions.add(solution);
            }
        }

        this.processAPI(apiSolutions);
        this.processSoftware(softwareSolutions);
        this.processService(serviceSolutions);
    }

    private void processAPI(List<Solution__c> solutions) {
        if (!solutions.isEmpty()) {
            //DO SOMETHING
        }
    }

    private void processSoftware(List<Solution__c> solutions) {
        if (!solutions.isEmpty()) {
            //DO SOMETHING
        }
    }

    private void processService(List<Solution__c> solutions) {
        if (!solutions.isEmpty()) {
            //DO SOMETHING
        }
    }
}