force-app/main/default/objects/Logger_Event__e/fields/Exception_Data__c.field-meta.xml
<CustomField>
    <fullName>Exception_Data__c</fullName>
    <label>Exception Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/logger/Logger.cls
public without sharing class Logger {

    private LoggerContext context;

    public Logger(LoggerContext loggerContext) {
        this.context = loggerContext;
    }

    public void logAndThrowException(Exception e) {
        Logger_Event__e loggerEvent = new Logger_Event__e();
        loggerEvent.Exception_Data__c = e.getStackTraceString();
        EventBus.publish(loggerEvent);

        if (this.context == LoggerContext.AURA) {
            throw new AuraHandledException(e.getMessage());
        } else {
            throw e;
        }
    }
}