force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Exception_Data__c.field-meta.xml
<CustomField>
    <fullName>Exception_Data__c</fullName>
    <label>Exception Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Logger_Event__e/fields/Exception_Data__c.field-meta.xml
<CustomField>
    <fullName>Exception_Data__c</fullName>
    <label>Exception Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/logger/LoggerEventTriggerHandler.cls
public with sharing class LoggerEventTriggerHandler {

    private List<Logger_Event__e> loggerEvents = Trigger.new;

    public void logExceptions() {
        List<Log__c> logs = new List<Log__c>();
        for (Logger_Event__e loggerEvent : loggerEvents) {
            logs.add(new Log__c(
                    Exception_Data__c = loggerEvent.Exception_Data__c
            ));
        }
        insert logs;
    }
}